### ISSUE TITLE
KeyError: 'FrameId'

### ISSUE THREAD

**Issue by ssbilakeri** [uark-cviu/DyGLIP#9]
during evaluation im facing key error ad trace back is here, i ran the code without any changes

Traceback (most recent call last):
  File "graph_baseline.py", line 210, in <module>
    main(args)
  File "graph_baseline.py", line 183, in main
    summary = compare_dataframes(gt, ts)
  File "/home/mca/DyGLIP-master/Step3_Matching/motmetrics/apps/eval_motchallenge.py", line 73, in compare_dataframes
    accs.append(mm.utils.compare_to_groundtruth(gts[k], tsacc, 'iou', distth=0.5))
  File "/home/mca/DyGLIP-master/Step3_Matching/motmetrics/utils.py", line 185, in compare_to_groundtruth
    fid_to_fgt = dict(iter(gt.groupby('FrameId')))
  File "/home/mca/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py", line 7712, in groupby
    return DataFrameGroupBy(
  File "/home/mca/anaconda3/lib/python3.8/site-packages/pandas/core/groupby/groupby.py", line 882, in __init__
    grouper, exclusions, obj = get_grouper(
  File "/home/mca/anaconda3/lib/python3.8/site-packages/pandas/core/groupby/grouper.py", line 882, in get_grouper
    raise KeyError(gpr)
KeyError: 'FrameId'

**Comment by sirish-gambhira** [comment]
Hello @ssbilakeri.

I am also trying to run the DyGLIP pipeline in an end-to-end manner on [MCT Dataset](http://www.mct2014.com/). I generated the bounding boxes, re-id features, maskrcnn features using the Step 1. However, when trying to run Step 2 (test_emb_to_mot.py) to generate merged bounding boxes across multiple cameras, I am facing few issues. I also noticed that trained checkpoint files are missing in the repo. I wanted to know if you were able to run the evaluation pipeline. If so, it would be great if you could help me in this regard. 

Tagging @truongthanhdat @qkgia @pha-nguyen for better reach. 

Thank you for your time.
